[package]
name = "test-temp-file"
version = "0.1.0"
authors = ["ohaddahan <ohaddahan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
lazy_static = "1.4.0"
